apiVersion: apps/v1
kind: Deployment
metadata:
  name: adder-service-deployment
  labels:
    app: adder-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adder-service
  template:
    metadata:
      labels:
        app: adder-service
    spec:
      containers:
      - name: adder-service
        image: rparitosh/simple-adder-service:LATEST
        imagePullPolicy: Always
        ports:
          - containerPort: 9003
---

apiVersion: v1
kind: Service
metadata:
  name: adder-service
spec:
  selector:
    app: adder-service
  ports:
  - port: 9003
    targetPort: 9003
  type: NodePort

          
    
    

